branches/2012/UMS.Web/Areas/Admin/Controllers/ConfigController.cs
using System;
using System.Web;
using System.Web.Mvc;
using UMS.Core.Data.Models.Config;
using UMS.Core.Data.Models.Directory;
using UMS.Core.Data.Repository;
using UMS.Core.Logic.Config;
using UMS.Web.ViewModels;
using UMS.Core.Logic.Directory;

namespace UMS.Web.Areas.Admin.Controllers
{
    public class ConfigController : Controller
    {
        //
        // GET: /Config/
        public ActionResult Index()
        {
            return View("Summary");
        }

        public ActionResult Summary()
        {
            return View();
        }

        public ActionResult Directory()
        {
            var dir = new Connections().GetDirectorySettings();
            return View(dir);
        }

        [HttpPost]
        public ActionResult Directory(DirectorySetting dir)
        {
            if (ModelState.IsValid)
            {
                var c = new Connections();
                c.SetDirectorySettings(dir);

                return RedirectToAction("Directory");
            }

            ViewData["Result"] = new HtmlString("<span class=\"failure\">Failed! The data provided was not valid.</span>");
            return View();
        }

        public ActionResult Database()
        {
            var db = new Connections().GetDatabaseSettings();
            return View(db);
        }

        public ActionResult Groups()
        {
            ViewData["Groups"] = Settings.Get<string>("GroupsToIgnore");
            return View();
        }

        [HttpPost]
        public ActionResult Groups(string groups)
        {
            try
            {
                Settings.Put("GroupsToIgnore", groups);
                return RedirectToAction("Groups");
            }
            catch (Exception)
            {
                ViewData["Result"] = new HtmlString("<span class=\"failure\">Failed! Could not save the groups.</span>");
                return View();
            }
        }

        public ActionResult Offline()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Offline(OfflineSetting offline)
        {
            if (ModelState.IsValid)
            {
                var s = new Core.Logic.Config.System();
                s.TakeOffline(offline.Message);

                return RedirectToAction("Offline");
            }

            ViewData["Result"] = new HtmlString("<span class=\"failure\">Failed! Input was not valid.</span>");
            return View();
        }

        public ActionResult Home()
        {
            var s = new HomeSettings
                        {
                            WeatherSetting =
                                {
                                    IsEnabled = Settings.Get<bool>("EnableWeather"),
                                    ApiKey = Settings.Get<string>("WeatherApiKey")
                                },
                            WallPostSetting =
                                {
                                    IsOverrideEnabled = Settings.Get<bool>("OverrideWallPosts"),
                                    RssOverrideUrl = Settings.Get<string>("WallPostRssUrl")
                                }
                        };

            return View(s);
        }

        [HttpPost]
        public ActionResult Home(HomeSettings settings)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Settings.Put("EnableWeather", settings.WeatherSetting.IsEnabled);
                    Settings.Put("WeatherApiKey", String.IsNullOrWhiteSpace(settings.WeatherSetting.ApiKey) ? "" : settings.WeatherSetting.ApiKey);
                    Settings.Put("OverrideWallPosts", settings.WallPostSetting.IsOverrideEnabled);
                    Settings.Put("WallPostRssUrl", String.IsNullOrWhiteSpace(settings.WallPostSetting.RssOverrideUrl) ? "" : settings.WallPostSetting.RssOverrideUrl);
                    return RedirectToAction("Home");
                }
                catch (Exception ex)
                {
                    ViewData["Result"] = new HtmlString("<span class=\"failure\">Failed! Could not save all settings</span>");
                }
                return View();
            }
            ViewData["Result"] = new HtmlString("<span class=\"failure\">Failed! Input was not valid.</span>");
            return View();
        }

        public ActionResult PasswordReminder()
        {
            var p = new PasswordReminder();
            return View(Core.Logic.Directory.PasswordReminder.GetSettings());
        }

        [HttpPost]
        public ActionResult PasswordReminder(PasswordReminderSetting settings)
        {
            var p = new PasswordReminder();
            var r = Core.Logic.Directory.PasswordReminder.UpdateSettings(settings);
            if (r)
            {
                ViewData["Result"] = new HtmlString("<span class=\"ok\">Success! Saved the changes.</span>");
            }
            else
            {
                ViewData["Result"] = new HtmlString("<span class=\"failure\">Failed! Could not save all settings</span>");
            }
            return View(Core.Logic.Directory.PasswordReminder.GetSettings());
        }
    }
}

branches/2012/UMS.Web/Controllers/MeController.cs
using System.Web.Mvc;
using UMS.Core.Data.Models.Directory;

namespace UMS.Web.Controllers
{
    public class MeController : Controller
    {
        //
        // GET: /Me/
        public ActionResult Index()
        {
            return View(Session["User"] as User);
        }

        public ActionResult Account()
        {
            return View(Session["User"] as User);
        }

        public ActionResult Password()
        {
            ViewData["User"] = Session["User"] as User;
            return View();
        }

        public ActionResult Photo()
        {
            return View();
        }
    }
}

branches/2012/UMS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="utf-8" />
    <title>uManage - @ViewBag.Title</title>
    <link rel="SHORTCUT ICON" href="/Images/UMS.ico" />
    <link rel="icon" type="image/vnd.microsoft.icon" href="/Images/UMS.ico" />
    <link rel="icon" type="image/png" href="/Images/UMS.png" />
    @Styles.Render("~/bundles/css/reset", "~/bundles/css")
    @RenderSection("Head", false)
</head>
<body>
    <div id="page">
        <div id="header">
            <div class="columns">
                <div class="left">
                    <a href="/">
                        <img src="@Url.Content("~/Images/Logo.png")" alt="Logo"/>
                    </a>
                </div>
                <div class="right">
                    <div class="columns">
                        <div class="left user-info">
                            <a href="/Me" class="name">Brent Pabst</a>
                            <br />
                            @Html.ActionLink("Administration", "Index", "Config", new { area = "Admin" }, new { })
                        </div>
                        <div class="right user-image">
                            <a href="/Me/Photo" title="Change My Photo">
                                <img src="@Url.Content("~/Images/No-Photo.png")" alt="User Photo" width="52px" height="52px"/>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="nav">
            @RenderSection("Nav", false)
        </div>
        <div id="content">
            @RenderBody()
        </div>
        <div id="footer">
            A <strong>203 Enterprises</strong> Project
            <br />
            <em>@Dns.GetHostEntry("localhost").HostName.ToLower()</em>
        </div>
    </div>
    @Scripts.Render("~/bundles/modernizr", "~/bundles/jquery", "~/bundles/ums")
    @RenderSection("Script", false)
</body>
</html>

branches/2012/UMS.Web/Views/Shared/_PasswordNotice.cshtml
@using UMS.Core.Enums
@using UMS.Core.Logic.App
@model UMS.Core.Data.Models.Directory.User
@{
    var p = Users.GetPasswordNotification(Model);
    var cssClass = "";
}
@if (p.Type != PasswordNotificationType.None)
{
    switch (p.Type)
    {
        case PasswordNotificationType.Reminder:
            cssClass = "ok-box";
            break;
        case PasswordNotificationType.Warning:
            cssClass = "warning-box";
            break;
        case PasswordNotificationType.Error:
            cssClass = "error-box";
            break;
    }
    <div class="box @cssClass">
        <div class="head">
            Password Expiration Reminder
        </div>
        <p>
            @Model.FirstName, your password expires
            <abbr id="passwordReminder" title="@String.Format("{0:s}", p.ExpirationDate)">
            </abbr>
            . You can change your password @Html.ActionLink("here", "Password", "Me").
        </p>
        @if (!String.IsNullOrWhiteSpace(p.AdditionalText))
        {
                
            <p>@p.AdditionalText</p>
        }
    </div>
}