branches/2012/UMS.Web/Areas/Admin/Controllers/LocationsController.cs
using System;
using System.Data;
using System.Web.Mvc;
using UMS.Core.Data.Models.App;
using UMS.Core.Data.Repository;

namespace UMS.Web.Areas.Admin.Controllers
{
    public class LocationsController : Controller
    {
        private readonly LocationRepository _repo = new LocationRepository();

        //
        // GET: /Locations/

        public ActionResult Index()
        {
            return View(_repo.All);
        }

        //
        // GET: /Locations/Details

        public ActionResult Details(Guid? id)
        {
            return id.HasValue ? View(_repo.Find(id.Value)) : View();
        }

        //
        // POST: /Locations/Details

        [HttpPost]
        public ActionResult Details(Location location)
        {
            try
            {
                ModelState["LocationId"].Errors.Clear();
                ModelState["IsEnabled"].Errors.Clear();
                if (ModelState.IsValid)
                {
                    _repo.InsertOrUpdate(location);
                    _repo.Save();

                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (DataException ex)
            {
                ModelState.AddModelError("dataError", ex);
                return View();
            }
        }
    }
}

branches/2012/UMS.Web/Areas/Admin/Views/Locations/Details.cshtml
@model UMS.Core.Data.Models.App.Location
@{
    var edit = Model != null;

    ViewBag.Title = edit ? "Edit Location" : "Add Location";
    Layout = "~/Areas/Admin/Views/Shared/_Config.cshtml";
}
@section Head
{
    @Styles.Render("~/bundles/css/jquery")
}
<div class="box">
    <div class="head">
        @if (edit)
        {<text>Edit Location</text>}
        else
        {<text>Add A Location</text>}
    </div>
    @using (Html.BeginForm("Details", "Locations", FormMethod.Post, new { id = "AddLocation" }))
    {
        @Html.EditorForModel()
        <input type="submit" value="Save Changes" />
        <text>&nbsp;&nbsp;</text>@Html.ActionLink("Cancel", "Index", "Locations", new { @class = "action prev" })
    }
</div>
@section Script
{
    <script type="text/javascript">
        $(function() {
            var edit = @edit.ToString().ToLower();
            if (!edit) {
                $("#IsEnabled").attr("disabled", "disabled").attr("checked", "checked");
            }
            $("#AddLocation").makeValidationInline();
        });
    </script>
}

branches/2012/UMS.Web/Areas/Admin/Views/Locations/Index.cshtml
@model IQueryable<UMS.Core.Data.Models.App.Location>
@{
    ViewBag.Title = "Locations";
    Layout = "~/Areas/Admin/Views/Shared/_Config.cshtml";
}
@{
    var grid = new WebGrid(Model, canPage: false);
}
<div class="box">
    <div class="head">
        Active Directory Locations
    </div>
    <p>
        These settings control the different locations your organization has as well as
        the active directory links for each location. Each location can have its own directory
        and new user configuration settings however they can be identical to other locations.
    </p>
    @Html.ActionLink("Add Location", "Details", "Locations", new { @class = "action next" })
    @* ReSharper disable Html.PathError *@
    @if (Model.Any())
    {
        @grid.GetHtml(tableStyle: "data", columns: grid.Columns(
            grid.Column(columnName: "Name", header: "Location Name", style: "link", format: @<text><a href="/Admin/Locations/Details/@item.LocationId">@item.Name</a></text>),
            grid.Column(columnName: "OrgName", header: "Organization"),
            grid.Column(columnName: "Directory", header: "Directory"),
            grid.Column("IsEnabled", "Active", @<text>@if (item.IsEnabled)
                                                      { <text>Yes</text> }
                                                      else
                                                      { <text>No</text> }</text>)))
    }
    else
    {
        <span class="empty">No locations are currently configured!</span>
    }
    @* ReSharper restore Html.PathError *@
</div>