branches/2012/UMS.Web/Areas/Admin/Controllers/WallController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UMS.Core.Data.Models.App;
using UMS.Core.Data.Repository;
using System.Data;

namespace UMS.Web.Areas.Admin.Controllers
{
    public class WallController : Controller
    {
        private WallPostRepository _repo = new WallPostRepository();

        //
        // GET: /Admin/Wall/

        public ActionResult Index()
        {
            return View(_repo.All.OrderByDescending(p => p.PublishDate));
        }

        public ActionResult Details(Guid? id)
        {
            return id.HasValue ? View(_repo.Find(id.Value)) : View();
        }

        [HttpPost]
        public ActionResult Details(WallPost post)
        {
            try
            {
                ModelState["PostId"].Errors.Clear();
                if (ModelState.IsValid)
                {
                    _repo.InsertOrUpdate(post);
                    _repo.Save();
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (DataException ex)
            {
                ModelState.AddModelError("dataError", ex);
                return View();
            }
        }

        public ActionResult Delete(Guid id)
        {
            try
            {
                _repo.Delete(id);
                _repo.Save();

                return RedirectToAction("Index");
            }
            catch (DataException ex)
            {
                // Log the error
                return RedirectToAction("Index");
            }
        }
    }
}

branches/2012/UMS.Web/Areas/Admin/Views/Wall/Details.cshtml
@model UMS.Core.Data.Models.App.WallPost
@{
    var edit = Model != null;
    ViewBag.Title = edit ? "Edit Wall Post" : "Add Wall Post";
    Layout = "~/Areas/Admin/Views/Shared/_Config.cshtml";
}
@section Head
{
    @Styles.Render("~/bundles/css/jquery")
}
<div class="box">
    <div class="head">
        @if (edit)
        {<text>Edit Wall Post</text>}
        else
        {<text>Add Wall Post</text>}
    </div>
    @using (Html.BeginForm("Details", "Wall", FormMethod.Post, new { id = "AddPost" }))
    {
        @Html.EditorFor(w => w.PostId)
        <div>
            @Html.LabelFor(w => w.IsDraft)
        </div>
        <div>
            @Html.EditorFor(w => w.IsDraft)
            @Html.ValidationMessageFor(w => w.IsDraft)
        </div>
        <div>
            @Html.LabelFor(w => w.PublishDate)
        </div>
        <div>
            @Html.EditorFor(w => w.PublishDate)
            @Html.ValidationMessageFor(w => w.PublishDate)
        </div>
        <div>
            @Html.LabelFor(w => w.Title)
        </div>
        <div>
            @Html.EditorFor(w => w.Title)
            @Html.ValidationMessageFor(w => w.Title)
        </div>
        <div>
            @Html.LabelFor(w => w.Body)
        </div>
        <div>
            @Html.TextAreaFor(w => w.Body)
            @Html.ValidationMessageFor(w => w.Body)
        </div>
        <br />
        <input type="submit" value="Save Changes" />
        <text>&nbsp;&nbsp;</text>@Html.ActionLink("Cancel", "Index", "Wall", new { @class = "action prev" })
    }
</div>
@section Script
{
    @Scripts.Render("~/bundles/tinymce")
    <script type="text/javascript">
        $(function () {
            $("#AddPost").makeValidationInline();

            $("#PublishDate").datepicker();
            if ($("#PublishDate").val()=="") {
                $("#PublishDate").val("@DateTime.Now.ToShortDateString()");
            }
            
            $('#Body').tinymce({
                script_url: "@Url.Content("~/Scripts/tinymce/tiny_mce.js")",
                theme: "simple",
                height: "200",
                width: "500",
                verify_html: false
            });
        });
    </script>
}

branches/2012/UMS.Web/Areas/Admin/Views/Wall/Index.cshtml
@model IOrderedQueryable<UMS.Core.Data.Models.App.WallPost>
@{
    ViewBag.Title = "Wall Posts";
    Layout = "~/Areas/Admin/Views/Shared/_Config.cshtml";
    var grid = new WebGrid(Model);
}
@section Head
{
    @Styles.Render("~/bundles/css/jquery")
}
<div class="box">
    <div class="head">
        Wall Posts
    </div>
    <p>
        Wall Posts are uManage's version of a blog. It allows you to post messages, alerts
        or really anything you want to tell users about. You can save posts for later and
        even schedule posts to publish in the future as well.
    </p>
    @Html.ActionLink("Add Wall Post", "Details", "Posts", new { @class = "action next" })
    @* ReSharper disable Html.PathError *@
    @if (Model.Any())
    {
        @grid.GetHtml(tableStyle: "data", columns: grid.Columns(
             grid.Column(style: "icon clear-fix", format: @<text><a class="delete" href="/Admin/Wall/Delete/@item.PostId">&nbsp;</a><a class="edit" href="/Admin/Wall/Details/@item.PostId">&nbsp;</a></text>),
                 grid.Column("Title"),
             grid.Column("PublishDate", "Publish Date", @<text>@item.PublishDate.ToShortDateString()</text>),
                 grid.Column("IsDraft", "Draft?", @<text>@if (item.IsDraft)
                                                         { <text>Yes</text> }
                                                         else
                                                         { <text>No</text> }</text>)
                                   ))
    }
    else
    {
        <span class="empty">No wall posts exist.</span>
    }
    @* ReSharper restore Html.PathError *@
</div>
@section Script
{
    <script type="text/javascript">
        $(function () {
        });
    </script>
}